### ISSUE TITLE
Can't find Node 

### ISSUE THREAD

**Issue by felipetesc** [sublimelsp/LSP-file-watcher-chokidar#2]
Hello! I'm trying to use your package but I'm finding an issue. When I start sublime I get the message: 
"Could not start LSP-file-watcher-chokidar due to not being able to find Node.js runtime..."
However Node is installed, and I it's on the path:

When I run: _**node --version**_ I get _**v18.4.0**_

Can I define node path using any configuration file ?

**Comment by rchl** [comment]
This is because ST doesn't see the same PATH as your terminal does. Here is an explanation how to fix it: https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers

**Comment by felipetesc** [comment]
> This is because ST doesn't see the same PATH as your terminal does. Here is an explanation on how to fix it: https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers

Thank you.
